# homepage:
#     path:   /
#     defaults:  { _controller: FOSUserBundle:Security:login }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_company:
    resource: "@AppBundle/Resources/config/routing/company.yml"
    prefix:   /company

app_job:
    resource: "@AppBundle/Resources/config/routing/job.yml"
    prefix:   /job    
    
